# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 324c1c695ff69aa8e5b3a25b80d9ad36bed225c62d413b8c505b3fe2771621a09b67be421d2b955c6ccc3be0b7c18bc9754535862c4df67dc22ff53c0ceac9d6

test:
  secret_key_base: 93eae2fd1f70eedf7a40ef7e6528371c2df08a3b85419f6368be71fc5d173f8f26675833188cdf2a0bca3b866b04fc18c896be554442b95347706103ce02f6dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
